### ISSUE TITLE
Why does the documentation say the non-strict assumptions are not guaranteed by the semantics.

### ISSUE THREAD

**Issue by tysonzero** [tov/memoize#11]
I thought Haskell's non-strict guarantees were pretty strong, namely that semantically things will not be evaluated unless necessary, operationally extra evaluation is allowed as long as it doesn't make a value become `_|_` that normally would not have been.

So I am confused as to what assumptions could have been made that are both not-guaranteed by the spec and yet still implemented by GHC, particularly since no `unsafePerformIO` or similar is used. I mean Haskell seems like it can't really get any more non-strict than it already is guaranteed by the spec, besides doing things like evaluating both sides of `&&` or `*` in parallel in case one side is `False` or `0` respectively.

**Comment by tov** [comment]
Haskell is certainly non-strict, and that means that the memoization technique in the package will always get the right result and never diverge if it shouldn’t. That is to say, it will be functionally/extensionally correct. But it may not do actually do memoization, because it depends on laziness/call-by-need. By my interpretation of the specification, call-by-name without any kind of laziness/memoization is allowed. (Though please correct me if I'm wrong.) If that were the case in some Haskell implementation, then the memoization this library ostensibly provides wouldn’t actually happen. Furthermore, a Haskell that does speculative forcing (which I believe to be allowed) could speculatively build a pretty big memo table (depending on how it decides when to stop), which is not what we usually mean by memoization.

**Comment by tysonzero** [comment]
Ah I totally forgot about that. Yeah I think technically call-by-need is not explicitly required by the spec, although I haven't read it in depth enough to know for sure.
